linters:
    BorderZero:
        enabled: false
    CapitalizationInSelector:
        enabled: true
    ColorKeyword:
        enabled: true
    Comment:
        enabled: true
    DebugStatement:
        enabled: true
    DeclarationOrder:
        enabled: true
    DuplicateProperty:
        enabled: true
    DuplicateProperty:
        enabled: true
    ElsePlacement:
        enabled: true
    EmptyLineBetweenBlocks:
        enabled: true
    EmptyRule:
        enabled: true
    FinalNewline:
        enabled: true
    HexLength:
        enabled: true
    HexNotation:
        enabled: true
        style: lowercase
    HexValidation:
        enabled: true
    IdWithExtraneousSelector:
        enabled: true
    Indentation:
        enabled: true
        width: 4
    LeadingZero:
        enabled: true
        style: include_zero
    MergeableSelector:
        enabled: true
    NameFormat:
        enabled: true
    PlaceholderInExtend:
        enabled: true
    PropertySortOrder:
        enabled: true
    PropertySpelling:
        enabled: true
    SelectorDepth:
        max_depth: 4
        enabled: true
    Shorthand:
        enabled: true
    SingleLinePerSelector:
        enabled: true
    SpaceAfterComma:
        enabled: true
    SpaceAfterPropertyColon:
        enabled: true
    SpaceAfterPropertyName:
        enabled: true
    SpaceBeforeBrace:
        enabled: true
    SpaceBetweenParens:
        enabled: true
    StringQuotes:
        enabled: true
        style: single_quotes
    TrailingSemicolonAfterPropertyValue:
        enabled: true
    UnnecessaryMantissa:
        enabled: true
    UrlFormat:
        enabled: true
    UrlQuotes:
        enabled: true
    ZeroUnit:
        enabled: true

